server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  cloud:g
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: analytics-service
          uri: lb://ANALYTICS-SERVICE
          predicates:
              - Path=/analytics/**