eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id:
          uri:
          predicates:
            - Path=/services/{segment}