server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-user:5432/user_db
    username: Auser
    pass: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG